# Generated by Django 5.2.7 on 2025-10-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoAgentSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=100)),
                ('reply_to', models.JSONField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_stack', models.JSONField(default=list)),
                ('conversation_history', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'agent_session',
            },
        ),
    ]
