# Generated by Django 5.2.6 on 2025-10-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_toolkit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoagentsession',
            name='running_tools',
            field=models.JSONField(default=list),
        ),
    ]
